version: '2'
services:
    imextract-app:
        image: imextract
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://imextract-mysql:3306/imextract?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    imextract-mysql:
        extends:
            file: mysql.yml
            service: imextract-mysql
